# Generated by Django 5.0.3 on 2024-05-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lojistas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="nome_produto",
            field=models.CharField(
                default="sorvete",
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Nome do Produto",
            ),
        ),
    ]
