# Generated by Django 5.0.3 on 2024-05-19 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lojistas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="custo",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Custo",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Preço",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome_produto",
            field=models.CharField(
                default="sorvete",
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Nome do Produto",
            ),
        ),
    ]
