from django.db import migrations
from django.db import transaction


def create_objects_from_dict(apps, schema_editor):
    print("Cadastrando produtos...")
    LojistasModel = apps.get_model('lojistas', 'Produto')
    data_dict = [{'codigo': 91690,
  'nome_produto': 'Araticum (Massa 5 Litros)',
  'descricao': 'M5L ARATICUM',
  'custo': 66.0,
  'preco': 116.55,
  'categoria': 'massa',
  'subcategoria': 'M5L'},
 {'codigo': 91695,
  'nome_produto': 'Buriti (Massa 5 Litros)',
  'descricao': 'M5L BURITI',
  'custo': 66.0,
  'preco': 116.55,
  'categoria': 'massa',
  'subcategoria': 'M5L'},
 {'codigo': 91700,
  'nome_produto': 'Mangaba (Massa 5 Litros)',
  'descricao': 'M5L MANGABA',
  'custo': 66.0,
  'preco': 116.55,
  'categoria': 'massa',
  'subcategoria': 'M5L'},
 {'codigo': 91705,
  'nome_produto': 'Murici (Massa 5 Litros)',
  'descricao': 'M5L MURICI',
  'custo': 66.0,
  'preco': 116.55,
  'categoria': 'massa',
  'subcategoria': 'M5L'},
 {'codigo': 91710,
  'nome_produto': 'Pequi (Massa 5 Litros)',
  'descricao': 'M5L PEQUI',
  'custo': 66.0,
  'preco': 116.55,
  'categoria': 'massa',
  'subcategoria': 'M5L'},
 {'codigo': 91863,
  'nome_produto': 'Açai com cupuaçu (Massa Açaí)',
  'descricao': 'MA AÇAI COM CUPUAÇU',
  'custo': 187.0,
  'preco': 334.95,
  'categoria': 'massa',
  'subcategoria': 'MA'},
 {'codigo': 91865,
  'nome_produto': 'Açai com ninho (Massa Açaí)',
  'descricao': 'MA AÇAI COM NINHO',
  'custo': 187.0,
  'preco': 334.95,
  'categoria': 'massa',
  'subcategoria': 'MA'},
 {'codigo': 95870,
  'nome_produto': 'Açai médio (Massa Açaí)',
  'descricao': 'MA AÇAI MÉDIO',
  'custo': 145.2,
  'preco': 282.45,
  'categoria': 'massa',
  'subcategoria': 'MA'},
 {'codigo': 91860,
  'nome_produto': 'Açai premium (Massa Açaí)',
  'descricao': 'MA AÇAI PREMIUM',
  'custo': 187.0,
  'preco': 334.95,
  'categoria': 'massa',
  'subcategoria': 'MA'},
 {'codigo': 91580,
  'nome_produto': 'Abacaxi com hortelã (Massa Especial)',
  'descricao': 'ME ABACAXI COM HORTELÃ',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91630,
  'nome_produto': 'Avelã com chocolate (Massa Especial)',
  'descricao': 'ME AVELÃ COM CHOCOLATE',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91585,
  'nome_produto': 'Bacuri (Massa Especial)',
  'descricao': 'ME BACURI',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91590,
  'nome_produto': 'Bombom (Massa Especial)',
  'descricao': 'ME BOMBOM',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91595,
  'nome_produto': 'Café com leite (Massa Especial)',
  'descricao': 'ME CAFÉ COM LEITE',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91600,
  'nome_produto': 'Cajamanga (Massa Especial)',
  'descricao': 'ME CAJAMANGA',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91602,
  'nome_produto': 'Cappuccino (Massa Especial)',
  'descricao': 'ME CAPPUCCINO',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91605,
  'nome_produto': 'Capuccino (Massa Especial)',
  'descricao': 'ME CAPUCCINO',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91610,
  'nome_produto': 'Castanha do pará (Massa Especial)',
  'descricao': 'ME CASTANHA DO PARÁ',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91495,
  'nome_produto': 'Chocomenta (Massa Especial)',
  'descricao': 'ME CHOCOMENTA',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91615,
  'nome_produto': 'Cookie (Massa Especial)',
  'descricao': 'ME COOKIE',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91620,
  'nome_produto': 'Cupuaçu (Massa Especial)',
  'descricao': 'ME CUPUAÇU',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91625,
  'nome_produto': 'Doce de leite (Massa Especial)',
  'descricao': 'ME DOCE DE LEITE',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91635,
  'nome_produto': 'Graviola (Massa Especial)',
  'descricao': 'ME GRAVIOLA',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91640,
  'nome_produto': 'Iogurte com amarena (Massa Especial)',
  'descricao': 'ME IOGURTE COM AMARENA',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91645,
  'nome_produto': 'Jabuticaba (Massa Especial)',
  'descricao': 'ME JABUTICABA',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91530,
  'nome_produto': 'Maltine branco (Massa Especial)',
  'descricao': 'ME MALTINE BRANCO',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91535,
  'nome_produto': 'Maltine preto (Massa Especial)',
  'descricao': 'ME MALTINE PRETO',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91650,
  'nome_produto': 'Morango fruta (Massa Especial)',
  'descricao': 'ME MORANGO FRUTA',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91655,
  'nome_produto': 'Ninho com abacaxi (Massa Especial)',
  'descricao': 'ME NINHO COM ABACAXI',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91660,
  'nome_produto': 'Ninho com ameixa (Massa Especial)',
  'descricao': 'ME NINHO COM AMEIXA',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91665,
  'nome_produto': 'Ninho com figo (Massa Especial)',
  'descricao': 'ME NINHO COM FIGO',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91670,
  'nome_produto': 'Ninho com morango (Massa Especial)',
  'descricao': 'ME NINHO COM MORANGO',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91675,
  'nome_produto': 'Ninho trufado (Massa Especial)',
  'descricao': 'ME NINHO TRUFADO',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91555,
  'nome_produto': 'Passas ao run (Massa Especial)',
  'descricao': 'ME PASSAS AO RUN',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91680,
  'nome_produto': 'Petit gateau (Massa Especial)',
  'descricao': 'ME PETIT GATEAU',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91685,
  'nome_produto': 'Pistache (Massa Especial)',
  'descricao': 'ME PISTACHE',
  'custo': 158.4,
  'preco': 300.3,
  'categoria': 'massa',
  'subcategoria': 'ME'},
 {'codigo': 91460,
  'nome_produto': 'Abacaxi (Massa Tradicional)',
  'descricao': 'MT ABACAXI',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91465,
  'nome_produto': 'Ameixa (Massa Tradicional)',
  'descricao': 'MT AMEIXA',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91470,
  'nome_produto': 'Amendoim (Massa Tradicional)',
  'descricao': 'MT AMENDOIM',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91475,
  'nome_produto': 'Banana (Massa Tradicional)',
  'descricao': 'MT BANANA',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91480,
  'nome_produto': 'Chiclete (Massa Tradicional)',
  'descricao': 'MT CHICLETE',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91485,
  'nome_produto': 'Chocolate (Massa Tradicional)',
  'descricao': 'MT CHOCOLATE',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91490,
  'nome_produto': 'Chocolate branco (Massa Tradicional)',
  'descricao': 'MT CHOCOLATE BRANCO',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91500,
  'nome_produto': 'Coco branco (Massa Tradicional)',
  'descricao': 'MT COCO BRANCO',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91505,
  'nome_produto': 'Creme (Massa Tradicional)',
  'descricao': 'MT CREME',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91510,
  'nome_produto': 'Flocos (Massa Tradicional)',
  'descricao': 'MT FLOCOS',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91515,
  'nome_produto': 'Frutas do bosque (Massa Tradicional)',
  'descricao': 'MT FRUTAS DO BOSQUE',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91520,
  'nome_produto': 'Leite condensado (Massa Tradicional)',
  'descricao': 'MT LEITE CONDENSADO',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91525,
  'nome_produto': 'Limão suíço (Massa Tradicional)',
  'descricao': 'MT LIMÃO SUÍÇO',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91540,
  'nome_produto': 'Maracujá (Massa Tradicional)',
  'descricao': 'MT MARACUJÁ',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91545,
  'nome_produto': 'Milho verde (Massa Tradicional)',
  'descricao': 'MT MILHO VERDE',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91550,
  'nome_produto': 'Morango leite (Massa Tradicional)',
  'descricao': 'MT MORANGO LEITE',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91551,
  'nome_produto': 'Napolitano (Massa Tradicional)',
  'descricao': 'MT NAPOLITANO',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91560,
  'nome_produto': 'Pavê italiano (Massa Tradicional)',
  'descricao': 'MT PAVÊ ITALIANO',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91565,
  'nome_produto': 'Tapioca (Massa Tradicional)',
  'descricao': 'MT TAPIOCA',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91570,
  'nome_produto': 'Uva (Massa Tradicional)',
  'descricao': 'MT UVA',
  'custo': 132.0,
  'preco': 232.58,
  'categoria': 'massa',
  'subcategoria': 'MT'},
 {'codigo': 91415,
  'nome_produto': 'Açaí com leite condensado (Paleta)',
  'descricao': 'PA AÇAÍ COM LEITE CONDENSADO',
  'custo': 5.5,
  'preco': 10.19,
  'categoria': 'picole',
  'subcategoria': 'PA'},
 {'codigo': 91420,
  'nome_produto': 'Chocolate com trufa (Paleta)',
  'descricao': 'PA CHOCOLATE COM TRUFA',
  'custo': 5.5,
  'preco': 10.19,
  'categoria': 'picole',
  'subcategoria': 'PA'},
 {'codigo': 91425,
  'nome_produto': 'Coco com trufa (Paleta)',
  'descricao': 'PA COCO COM TRUFA',
  'custo': 5.5,
  'preco': 10.19,
  'categoria': 'picole',
  'subcategoria': 'PA'},
 {'codigo': 91430,
  'nome_produto': 'Maracujá com leite condensado (Paleta)',
  'descricao': 'PA MARACUJÁ COM LEITE CONDENSADO',
  'custo': 5.5,
  'preco': 10.19,
  'categoria': 'picole',
  'subcategoria': 'PA'},
 {'codigo': 91435,
  'nome_produto': 'Morango com leite condensado (Paleta)',
  'descricao': 'PA MORANGO COM LEITE CONDENSADO',
  'custo': 5.5,
  'preco': 10.19,
  'categoria': 'picole',
  'subcategoria': 'PA'},
 {'codigo': 91440,
  'nome_produto': 'Ninho com trufa (Paleta)',
  'descricao': 'PA NINHO COM TRUFA',
  'custo': 5.5,
  'preco': 10.19,
  'categoria': 'picole',
  'subcategoria': 'PA'},
 {'codigo': 91285,
  'nome_produto': 'Abacaxi zero açúcar (Picolé Especial)',
  'descricao': 'PG ABACAXI ZERO AÇÚCAR',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91035,
  'nome_produto': 'Açai com ninho (Picolé Especial)',
  'descricao': 'PG AÇAI COM NINHO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91292,
  'nome_produto': 'Alfajor (Picolé Especial)',
  'descricao': 'PG ALFAJOR',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91340,
  'nome_produto': 'Avela com chocolate (Picolé Especial)',
  'descricao': 'PG AVELA COM CHOCOLATE',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91295,
  'nome_produto': 'Bacuri (Picolé Especial)',
  'descricao': 'PG BACURI',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91300,
  'nome_produto': 'Brigadeiro (Picolé Especial)',
  'descricao': 'PG BRIGADEIRO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91305,
  'nome_produto': 'Cajá-manga zero açúcar – não repor (Picolé Especial)',
  'descricao': 'PG CAJÁ-MANGA ZERO AÇÚCAR – NÃO REPOR',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91310,
  'nome_produto': 'Chocolate branco (Picolé Especial)',
  'descricao': 'PG CHOCOLATE BRANCO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91315,
  'nome_produto': 'Chocolate zero açúcar (Picolé Especial)',
  'descricao': 'PG CHOCOLATE ZERO AÇÚCAR',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91320,
  'nome_produto': 'Chocomenta (Picolé Especial)',
  'descricao': 'PG CHOCOMENTA',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91325,
  'nome_produto': 'Coco branco zero (Picolé Especial)',
  'descricao': 'PG COCO BRANCO ZERO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91335,
  'nome_produto': 'Doce de leite (Picolé Especial)',
  'descricao': 'PG DOCE DE LEITE',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91345,
  'nome_produto': 'Frutas do bosque (Picolé Especial)',
  'descricao': 'PG FRUTAS DO BOSQUE',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91350,
  'nome_produto': 'Maltine (Picolé Especial)',
  'descricao': 'PG MALTINE',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91355,
  'nome_produto': 'Morango zero açúcar (Picolé Especial)',
  'descricao': 'PG MORANGO ZERO AÇÚCAR',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91360,
  'nome_produto': 'Ninho (Picolé Especial)',
  'descricao': 'PG NINHO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91365,
  'nome_produto': 'Ninho com abacaxi (Picolé Especial)',
  'descricao': 'PG NINHO COM ABACAXI',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91370,
  'nome_produto': 'Ninho com morango (Picolé Especial)',
  'descricao': 'PG NINHO COM MORANGO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91373,
  'nome_produto': 'Ninho com morango zero (Picolé Especial)',
  'descricao': 'PG NINHO COM MORANGO ZERO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91375,
  'nome_produto': 'Ninho trufado (Picolé Especial)',
  'descricao': 'PG NINHO TRUFADO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 623,
  'nome_produto': 'Ninho trufado zero (Picolé Especial)',
  'descricao': 'PG NINHO TRUFADO ZERO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91380,
  'nome_produto': 'Passas ao run (Picolé Especial)',
  'descricao': 'PG PASSAS AO RUN',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91385,
  'nome_produto': 'Pé de moloque (Picolé Especial)',
  'descricao': 'PG PÉ DE MOLOQUE',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91390,
  'nome_produto': 'Skimo (Picolé Especial)',
  'descricao': 'PG SKIMO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91395,
  'nome_produto': 'Tentação (Picolé Especial)',
  'descricao': 'PG TENTAÇÃO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91400,
  'nome_produto': 'Torta de limão (Picolé Especial)',
  'descricao': 'PG TORTA DE LIMÃO',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91405,
  'nome_produto': 'Torta de maracujá (Picolé Especial)',
  'descricao': 'PG TORTA DE MARACUJÁ',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91410,
  'nome_produto': 'Uva zero açúcar (Picolé Especial)',
  'descricao': 'PG UVA ZERO AÇÚCAR',
  'custo': 3.3,
  'preco': 5.99,
  'categoria': 'picole',
  'subcategoria': 'PG'},
 {'codigo': 91443,
  'nome_produto': 'Chiclete (Picolé Kids)',
  'descricao': 'PK CHICLETE',
  'custo': 1.21,
  'preco': 2.42,
  'categoria': 'picole',
  'subcategoria': 'PK'},
 {'codigo': 91445,
  'nome_produto': 'Chocolate (Picolé Kids)',
  'descricao': 'PK CHOCOLATE',
  'custo': 1.21,
  'preco': 2.42,
  'categoria': 'picole',
  'subcategoria': 'PK'},
 {'codigo': 91450,
  'nome_produto': 'Groselha (Picolé Kids)',
  'descricao': 'PK GROSELHA',
  'custo': 1.21,
  'preco': 2.42,
  'categoria': 'picole',
  'subcategoria': 'PK'},
 {'codigo': 91455,
  'nome_produto': 'Mar azul (Picolé Kids)',
  'descricao': 'PK MAR AZUL',
  'custo': 1.21,
  'preco': 2.42,
  'categoria': 'picole',
  'subcategoria': 'PK'},
 {'codigo': 91457,
  'nome_produto': 'Morango (Picolé Kids)',
  'descricao': 'PK MORANGO',
  'custo': 1.21,
  'preco': 2.42,
  'categoria': 'picole',
  'subcategoria': 'PK'},
 {'codigo': 91458,
  'nome_produto': 'Uva (Picolé Kids)',
  'descricao': 'PK UVA',
  'custo': 1.21,
  'preco': 2.42,
  'categoria': 'picole',
  'subcategoria': 'PK'},
 {'codigo': 91876,
  'nome_produto': 'Açai com ninho (PMA15)',
  'descricao': 'PMA15 AÇAI COM NINHO',
  'custo': 34.1,
  'preco': 55.65,
  'categoria': 'pote',
  'subcategoria': 'PMA15'},
 {'codigo': 585,
  'nome_produto': 'Açai com cupuaçu (PMA15)',
  'descricao': 'PMA15 AÇAI COM CUPUAÇU',
  'custo': 34.1,
  'preco': 55.65,
  'categoria': 'pote',
  'subcategoria': 'PMA15'},
 {'codigo': 91875,
  'nome_produto': 'Açai premium (PMA15)',
  'descricao': 'PMA15 AÇAI PREMIUM',
  'custo': 34.1,
  'preco': 55.65,
  'categoria': 'pote',
  'subcategoria': 'PMA15'},
 {'codigo': 91800,
  'nome_produto': 'Avela com chocolate (Pote Massa Especial)',
  'descricao': 'PME AVELA COM CHOCOLATE',
  'custo': 24.2,
  'preco': 40.43,
  'categoria': 'pote',
  'subcategoria': 'PME'},
 {'codigo': 91785,
  'nome_produto': 'Cajamanga (Pote Massa Especial)',
  'descricao': 'PME CAJAMANGA',
  'custo': 24.2,
  'preco': 40.43,
  'categoria': 'pote',
  'subcategoria': 'PME'},
 {'codigo': 91727,
  'nome_produto': 'Chocomenta (Pote Massa Especial)',
  'descricao': 'PME CHOCOMENTA',
  'custo': 24.2,
  'preco': 40.43,
  'categoria': 'pote',
  'subcategoria': 'PME'},
 {'codigo': 91795,
  'nome_produto': 'Cupuaçu (Pote Massa Especial)',
  'descricao': 'PME CUPUAÇU',
  'custo': 24.2,
  'preco': 40.43,
  'categoria': 'pote',
  'subcategoria': 'PME'},
 {'codigo': 91815,
  'nome_produto': 'Morango fruta (Pote Massa Especial)',
  'descricao': 'PME MORANGO FRUTA',
  'custo': 24.2,
  'preco': 40.43,
  'categoria': 'pote',
  'subcategoria': 'PME'},
 {'codigo': 91820,
  'nome_produto': 'Ninho com abacaxi (Pote Massa Especial)',
  'descricao': 'PME NINHO COM ABACAXI',
  'custo': 24.2,
  'preco': 40.43,
  'categoria': 'pote',
  'subcategoria': 'PME'},
 {'codigo': 91825,
  'nome_produto': 'Ninho com morango (Pote Massa Especial)',
  'descricao': 'PME NINHO COM MORANGO',
  'custo': 24.2,
  'preco': 40.43,
  'categoria': 'pote',
  'subcategoria': 'PME'},
 {'codigo': 91830,
  'nome_produto': 'Ninho trufado (Pote Massa Especial)',
  'descricao': 'PME NINHO TRUFADO',
  'custo': 24.2,
  'preco': 40.43,
  'categoria': 'pote',
  'subcategoria': 'PME'},
 {'codigo': 91767,
  'nome_produto': 'Passas ao rum (Pote Massa Especial)',
  'descricao': 'PME PASSAS AO RUM',
  'custo': 24.2,
  'preco': 40.43,
  'categoria': 'pote',
  'subcategoria': 'PME'},
 {'codigo': 578,
  'nome_produto': 'Pistache (Pote Massa Especial)',
  'descricao': 'PME PISTACHE',
  'custo': 24.2,
  'preco': 40.43,
  'categoria': 'pote',
  'subcategoria': 'PME'},
 {'codigo': 91715,
  'nome_produto': 'Abacaxi ao leite (Pote Massa Tradicional)',
  'descricao': 'PMT ABACAXI AO LEITE',
  'custo': 22.0,
  'preco': 35.7,
  'categoria': 'pote',
  'subcategoria': 'PMT'},
 {'codigo': 91720,
  'nome_produto': 'Chocolate (Pote Massa Tradicional)',
  'descricao': 'PMT CHOCOLATE',
  'custo': 22.0,
  'preco': 35.7,
  'categoria': 'pote',
  'subcategoria': 'PMT'},
 {'codigo': 91730,
  'nome_produto': 'Coco branco (Pote Massa Tradicional)',
  'descricao': 'PMT COCO BRANCO',
  'custo': 22.0,
  'preco': 35.7,
  'categoria': 'pote',
  'subcategoria': 'PMT'},
 {'codigo': 91740,
  'nome_produto': 'Flocos (Pote Massa Tradicional)',
  'descricao': 'PMT FLOCOS',
  'custo': 22.0,
  'preco': 35.7,
  'categoria': 'pote',
  'subcategoria': 'PMT'},
 {'codigo': 91745,
  'nome_produto': 'Frutas do bosque (Pote Massa Tradicional)',
  'descricao': 'PMT FRUTAS DO BOSQUE',
  'custo': 22.0,
  'preco': 35.7,
  'categoria': 'pote',
  'subcategoria': 'PMT'},
 {'codigo': 91755,
  'nome_produto': 'Limao suíço (Pote Massa Tradicional)',
  'descricao': 'PMT LIMAO SUÍÇO',
  'custo': 22.0,
  'preco': 35.7,
  'categoria': 'pote',
  'subcategoria': 'PMT'},
 {'codigo': 91765,
  'nome_produto': 'Morango ao leite (Pote Massa Tradicional)',
  'descricao': 'PMT MORANGO AO LEITE',
  'custo': 22.0,
  'preco': 35.7,
  'categoria': 'pote',
  'subcategoria': 'PMT'},
 {'codigo': 91770,
  'nome_produto': 'Pave italiano (Pote Massa Tradicional)',
  'descricao': 'PMT PAVE ITALIANO',
  'custo': 22.0,
  'preco': 35.7,
  'categoria': 'pote',
  'subcategoria': 'PMT'},
 {'codigo': 91000,
  'nome_produto': 'Abacate (Picolé Tradicional)',
  'descricao': 'PT ABACATE',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91010,
  'nome_produto': 'Abacaxi fruta (Picolé Tradicional)',
  'descricao': 'PT ABACAXI FRUTA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91005,
  'nome_produto': 'Abacaxi leite (Picolé Tradicional)',
  'descricao': 'PT ABACAXI LEITE',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91015,
  'nome_produto': 'Açai (Picolé Tradicional)',
  'descricao': 'PT AÇAI',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91045,
  'nome_produto': 'Amendoim (Picolé Tradicional)',
  'descricao': 'PT AMENDOIM',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91050,
  'nome_produto': 'Amora (Picolé Tradicional)',
  'descricao': 'PT AMORA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91055,
  'nome_produto': 'Araticun (Picolé Tradicional)',
  'descricao': 'PT ARATICUN',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91060,
  'nome_produto': 'Banana (Picolé Tradicional)',
  'descricao': 'PT BANANA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91065,
  'nome_produto': 'Buriti (Picolé Tradicional)',
  'descricao': 'PT BURITI',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91070,
  'nome_produto': 'Cagaita (Picolé Tradicional)',
  'descricao': 'PT CAGAITA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91075,
  'nome_produto': 'Caja-manga (Picolé Tradicional)',
  'descricao': 'PT CAJA-MANGA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91080,
  'nome_produto': 'Cajuzinho (Picolé Tradicional)',
  'descricao': 'PT CAJUZINHO',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91085,
  'nome_produto': 'Castanha caju (Picolé Tradicional)',
  'descricao': 'PT CASTANHA CAJU',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91090,
  'nome_produto': 'Castanha pará (Picolé Tradicional)',
  'descricao': 'PT CASTANHA PARÁ',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91095,
  'nome_produto': 'Chocolate (Picolé Tradicional)',
  'descricao': 'PT CHOCOLATE',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91100,
  'nome_produto': 'Ciriguela (Picolé Tradicional)',
  'descricao': 'PT CIRIGUELA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91105,
  'nome_produto': 'Coalhada (Picolé Tradicional)',
  'descricao': 'PT COALHADA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91110,
  'nome_produto': 'Coco branco (Picolé Tradicional)',
  'descricao': 'PT COCO BRANCO',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91115,
  'nome_produto': 'Coco queimado (Picolé Tradicional)',
  'descricao': 'PT COCO QUEIMADO',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91120,
  'nome_produto': 'Cupuacu (Picolé Tradicional)',
  'descricao': 'PT CUPUACU',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91125,
  'nome_produto': 'Flocos (Picolé Tradicional)',
  'descricao': 'PT FLOCOS',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91130,
  'nome_produto': 'Goiaba (Picolé Tradicional)',
  'descricao': 'PT GOIABA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91135,
  'nome_produto': 'Graviola (Picolé Tradicional)',
  'descricao': 'PT GRAVIOLA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91140,
  'nome_produto': 'Groselha (Picolé Tradicional)',
  'descricao': 'PT GROSELHA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91145,
  'nome_produto': 'Jabuticaba (Picolé Tradicional)',
  'descricao': 'PT JABUTICABA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91150,
  'nome_produto': 'Jaca (Picolé Tradicional)',
  'descricao': 'PT JACA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91155,
  'nome_produto': 'Kiwi (Picolé Tradicional)',
  'descricao': 'PT KIWI',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91160,
  'nome_produto': 'Leite condensado (Picolé Tradicional)',
  'descricao': 'PT LEITE CONDENSADO',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91165,
  'nome_produto': 'Lichia (Picolé Tradicional)',
  'descricao': 'PT LICHIA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91170,
  'nome_produto': 'Limao fruta (Picolé Tradicional)',
  'descricao': 'PT LIMAO FRUTA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91175,
  'nome_produto': 'Limao suíço (Picolé Tradicional)',
  'descricao': 'PT LIMAO SUÍÇO',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91180,
  'nome_produto': 'Mamao (Picolé Tradicional)',
  'descricao': 'PT MAMAO',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91185,
  'nome_produto': 'Manga (Picolé Tradicional)',
  'descricao': 'PT MANGA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91190,
  'nome_produto': 'Mangaba (Picolé Tradicional)',
  'descricao': 'PT MANGABA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91200,
  'nome_produto': 'Maracuja fruta (Picolé Tradicional)',
  'descricao': 'PT MARACUJA FRUTA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91195,
  'nome_produto': 'Maracuja leite (Picolé Tradicional)',
  'descricao': 'PT MARACUJA LEITE',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91205,
  'nome_produto': 'Melancia (Picolé Tradicional)',
  'descricao': 'PT MELANCIA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91210,
  'nome_produto': 'Melao (Picolé Tradicional)',
  'descricao': 'PT MELAO',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91220,
  'nome_produto': 'Milho verde (Picolé Tradicional)',
  'descricao': 'PT MILHO VERDE',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91230,
  'nome_produto': 'Morango fruta (Picolé Tradicional)',
  'descricao': 'PT MORANGO FRUTA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91225,
  'nome_produto': 'Morango leite (Picolé Tradicional)',
  'descricao': 'PT MORANGO LEITE',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91235,
  'nome_produto': 'Murici (Picolé Tradicional)',
  'descricao': 'PT MURICI',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91240,
  'nome_produto': 'Olho de sogra – não repor (Picolé Tradicional)',
  'descricao': 'PT OLHO DE SOGRA – NÃO REPOR',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91245,
  'nome_produto': 'Pequi (Picolé Tradicional)',
  'descricao': 'PT PEQUI',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91250,
  'nome_produto': 'Pera (Picolé Tradicional)',
  'descricao': 'PT PERA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91255,
  'nome_produto': 'Romeu e julieta (Picolé Tradicional)',
  'descricao': 'PT ROMEU E JULIETA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91260,
  'nome_produto': 'Tamarindo (Picolé Tradicional)',
  'descricao': 'PT TAMARINDO',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91265,
  'nome_produto': 'Taperebá (Picolé Tradicional)',
  'descricao': 'PT TAPEREBÁ',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91270,
  'nome_produto': 'Tapioca (Picolé Tradicional)',
  'descricao': 'PT TAPIOCA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91275,
  'nome_produto': 'Umbú (Picolé Tradicional)',
  'descricao': 'PT UMBÚ',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'},
 {'codigo': 91280,
  'nome_produto': 'Uva (Picolé Tradicional)',
  'descricao': 'PT UVA',
  'custo': 2.2,
  'preco': 4.1,
  'categoria': 'picole',
  'subcategoria': 'PT'}]
    
    for item in data_dict:
        try:
            with transaction.atomic():
                LojistasModel.objects.create(**item)
        except Exception as e:
            print(f'Erro ao cadastrar produto: {e}')


class Migration(migrations.Migration):
    dependencies = [
        ("lojistas", "0002_produto_custo_produto_preco_and_more"),
    ]

    operations = [
        migrations.RunPython(create_objects_from_dict),
    ]
